FROM amazoncorretto:17-alpine
RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring
ARG DEPENDENCY=target/dependency
COPY ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY ${DEPENDENCY}/META-INF /app/META-INF
COPY ${DEPENDENCY}/BOOT-INF/classes /app
ENTRYPOINT ["java","-cp","app:app/lib/*","com.salesianostriana.dam.ejemploHolaMundo.EjemploHolaMundoApplication"]

#Te tienes que meter en target/dependency y poner esto en la terminal:  & 'C:\Program Files\Java\jdk-17\bin\jar.exe' -xf ..\ejemploHolaMundo-0.0.1-SNAPSHOT.jar